import Foundation

enum LocalizedPresentation {

    static func text(_ value: String) -> String {
        switch value {

        // MARK: General state

        case "Connected": return "Подключено"
        case "Connecting": return "Подключение"
        case "Offline": return "Не подключено"
        case "Failed": return "Ошибка"
        case "Unknown": return "Неизвестно"
        case "Available": return "Доступно"
        case "Unavailable": return "Недоступно"

        // MARK: Run state

        case "Queued": return "В очереди"
        case "Working": return "Выполняется"
        case "Done": return "Готово"
        case "Cancelled": return "Отменено"
        case "Interrupted": return "Прервано"

        // MARK: Run results

        case "Harness failed": return "Ошибка агента"
        case "No changes": return "Без изменений"
        case "Review blocked": return "Проверка заблокирована"
        case "Checks failed": return "Проверки не пройдены"
        case "Exhausted": return "Лимит исчерпан"
        case "Budget overshot": return "Бюджет превышен"
        case "Cost unverifiable": return "Стоимость не подтверждена"
        case "Not converged": return "Результат не сошёлся"
        case "Stuck/no progress": return "Нет прогресса"
        case "Workspace unavailable": return "Рабочее пространство недоступно"
        case "Time limit reached": return "Достигнут лимит времени"

        // MARK: Run mode

        case "Ask": return "Вопрос"
        case "Agent": return "Агент"
        case "Plan": return "План"
        case "Best-of-N": return "Лучший из вариантов"
        case "Max Attempts": return "Максимум попыток"
        case "Until Clean": return "До чистого результата"
        case "Create": return "Создать"
        case "Read-only Audit": return "Аудит без изменений"
        case "Unknown Mode": return "Неизвестный режим"

        // MARK: Review

        case "Reviewing": return "Проверка"
        case "Clean": return "Без замечаний"
        case "Changes requested": return "Нужны изменения"
        case "Winner": return "Победитель"
        case "Rejected": return "Отклонено"
        case "Proposed": return "Предложено"
        case "Accepted": return "Принято"
        case "Rebutted": return "Оспорено"
        case "Fixed": return "Исправлено"
        case "Accepted Risk": return "Риск принят"
        case "Duplicate": return "Дубликат"
        case "Stale": return "Устарело"
        case "Out of Scope": return "Вне области задачи"
        case "Insufficient": return "Недостаточно данных"
        case "Not reviewed": return "Не проверено"
        case "Running": return "Выполняется"
        case "Findings": return "Замечания"
        case "Error": return "Ошибка"

        // MARK: Workspace tabs

        case "Changes": return "Изменения"
        case "Artifacts": return "Артефакты"
        case "Evidence": return "Доказательства"
        case "Terminal": return "Терминал"

        // MARK: Access

        case "Read-only": return "Только чтение"
        case "Workspace write": return "Запись в рабочее пространство"
        case "Full access": return "Полный доступ"
        case "Inherit native": return "Наследовать нативный доступ"

        // MARK: Auth

        case "Login verified": return "Вход подтверждён"
        case "Login failed": return "Ошибка входа"
        case "Launching the native login…":
            return "Запуск нативного входа…"
        case "Waiting for you to finish the login":
            return "Ожидание завершения входа"
        case "Verifying the session…":
            return "Проверка сессии…"
        case "Cancelling…":
            return "Отмена…"
        case "Working…":
            return "Выполняется…"
        case "Timed out waiting for the login":
            return "Истекло время ожидания входа"
        case "Not supported for this harness":
            return "Не поддерживается этим агентом"
        case "Process termination is unconfirmed":
            return "Завершение процесса не подтверждено"

        // MARK: Account / quota

        case "Subscription": return "Подписка"
        case "API key": return "API-ключ"
        case "Scoped limits": return "Ограничения модели"
        case "exhausted": return "лимит исчерпан"
        case "cooldown": return "ожидание восстановления"

        // MARK: Workspace result

        case "Applied": return "Применено"
        case "Applied as branch": return "Применено как ветка"
        case "Committed": return "Создан коммит"
        case "PR opened": return "Pull Request открыт"
        case "Nothing to apply": return "Нет изменений для применения"
        case "Apply rejected": return "Применение отклонено"

        case "Engine offline.": return "Движок не подключён."
        case "Engine offline": return "Движок не подключён"
        case "Request failed.": return "Запрос не выполнен."
        case "Something went wrong. Try again.": return "Произошла ошибка. Попробуйте ещё раз."
        case "Settings stopped loading.": return "Загрузка настроек остановлена."
        case "Settings context changed while loading. Retry.": return "Контекст настроек изменился во время загрузки. Повторите попытку."
        case "Engine offline — reconnect to load settings.": return "Движок не подключён — переподключитесь для загрузки настроек."
        case "Engine offline — reconnect to check Git readiness.": return "Движок не подключён — переподключитесь для проверки готовности Git."
        case "Engine offline: reconnect and try again.": return "Движок не подключён — переподключитесь и попробуйте снова."
        case "Engine offline — reconnect to apply this thread.": return "Движок не подключён — переподключитесь, чтобы применить изменения этого чата."
        case "Run succeeded": return "Запуск завершён успешно"
        case "Run failed": return "Запуск завершился ошибкой"
        case "Run interrupted": return "Запуск прерван"
        case "Run status unknown": return "Статус запуска неизвестен"
        case "Claudexor needs your answer": return "Claudexor ожидает ваш ответ"
        case "Answer delivered": return "Ответ отправлен"
        case "Question closed — run cancelled": return "Вопрос закрыт — запуск отменён"
        case "Question timed out — continuing with assumptions": return "Время ожидания ответа истекло — выполнение продолжено с допущениями"
        case "Conflict — apply refused": return "Конфликт — применение отклонено"
        case "Runs": return "Запуски"
        case "No project": return "Без проекта"
        case "No project output in this thread": return "В этом чате пока нет результатов проекта"
        case "This thread hasn't produced changes, artifacts, or evidence yet.": return "В этом чате ещё нет изменений, артефактов или результатов."
        case "No run in this thread produced a patch.": return "Ни один запуск в этом чате не создал изменений."
        case "Run folder": return "Папка запуска"
        case "Thread title": return "Название чата"
        case "Empty file": return "Пустой файл"
        case "(empty file)": return "(пустой файл)"
        case "Loading…": return "Загрузка…"
        case "Sign-in code": return "Код входа"
        case "Complete the sign-in in your browser to finish.": return "Завершите вход в браузере."
        case "Engine offline: reconnect before storing a key.": return "Движок не подключён — переподключитесь перед сохранением ключа."
        case "Wait for the current action to finish.": return "Дождитесь завершения текущего действия."
        case "Enter the API key in the fallback field first.": return "Сначала введите API-ключ в резервное поле."
        case "The sign-in window closed. Get a new link first.": return "Окно входа закрыто. Сначала получите новую ссылку."
        case "Delivering the code to the sign-in…": return "Передача кода для входа…"
        case "Paste the code from the sign-in page first.": return "Сначала вставьте код со страницы входа."
        case "Log in": return "Войти"
        case "Retry check": return "Повторить проверку"
        case "Store key": return "Сохранить ключ"
        case "Reconnect": return "Переподключить"
        case "Setup state is still resolving": return "Состояние настройки всё ещё определяется"
        case "Native login is still active": return "Нативный вход всё ещё выполняется"
        case "Connecting with OpenSSH…": return "Подключение через OpenSSH…"
        case "SSH needs authentication. Click Connect to open its terminal.": return "Требуется авторизация SSH. Нажмите «Подключить», чтобы открыть терминал."
        case "Preparing the SSH authentication terminal…": return "Подготовка терминала авторизации SSH…"
        case "Finish SSH authentication in the terminal.": return "Завершите авторизацию SSH в терминале."
        case "Installing the remote runtime…": return "Установка удалённой среды выполнения…"
        case "Updating an incompatible runtime…": return "Обновление несовместимой среды выполнения…"
        case "Updating the remote runtime…": return "Обновление удалённой среды выполнения…"
        case "Interactive SSH authentication did not finish.": return "Интерактивная авторизация SSH не была завершена."
        case "Disconnected. Cached thread titles remain available.": return "Соединение разорвано. Сохранённые названия чатов остаются доступны."
        case "Downloading and verifying the signed runtime…": return "Загрузка и проверка подписанной среды выполнения…"
        case "The SSH tunnel is unavailable. Reconnect the host.": return "SSH-туннель недоступен. Переподключите хост."
        case "SSH needs authentication. Close the current terminal and click Connect.": return "Требуется авторизация SSH. Закройте текущий терминал и нажмите «Подключить»."
        case "Accounts": return "Аккаунты"
        case "Legacy default login": return "Старый вход по умолчанию"
        case "Accounts and quota are unavailable while the engine is offline.": return "Аккаунты и квоты недоступны, пока движок не подключён."
        case "Removed from Claudexor.": return "Удалено из Claudexor."
        case "Auto": return "Авто"
        case "Automatic (account pool)": return "Автоматически (пул аккаунтов)"
        case "Thread default": return "Настройка чата"
        case "Read-only intents never write": return "Режимы только для чтения не изменяют файлы"
        case "How much this turn may touch": return "Какой доступ разрешён для этого запуска"
        case "Delegate unavailable": return "Делегирование недоступно"
        case "No automatic expiry": return "Без автоматического истечения"
        case "Expiry unavailable": return "Срок действия недоступен"
        case "Route verified": return "Маршрут подтверждён"
        case "Model arg accepted": return "Параметр модели принят"
        case "Route unverified": return "Маршрут не подтверждён"
        case "Same-model fallback": return "Резерв на ту же модель"
        case "Verified final review clean.": return "Финальная проверка подтверждена: замечаний нет."
        case "Review produced findings.": return "Проверка выявила замечания."
        case "Review is running.": return "Проверка выполняется."
        case "Review failed.": return "Проверка завершилась ошибкой."
        case "Review ended with an error.": return "Проверка завершилась с ошибкой."
        case "Not reviewed.": return "Не проверено."
        case "Output pending": return "Результат ожидается"
        case "Output finalizing": return "Результат формируется"
        case "Diagnostic output": return "Диагностический результат"
        case "Output ready": return "Результат готов"
        case "Council": return "Совет агентов"
        case "Candidates": return "Кандидаты"
        case "Cross-family review": return "Перекрёстная проверка агентами"
        case "Thinking": return "Размышление"
        case "Appearance": return "Внешний вид"
        case "Applied to project": return "Применено к проекту"
        case "Open in workspace": return "Открыть в рабочем пространстве"
        case "Answer required": return "Требуется ответ"

        case "Retired external sandbox (full)": return "Устаревшая внешняя песочница (полный доступ)"
        case "Choose an active access profile for this historical thread before continuing.": return "Перед продолжением выберите действующий профиль доступа для этого старого чата."
        case "Add a second Claude, Codex, or agy account to control auto-switch here; Cursor accounts already switch automatically at a vendor limit.": return "Добавьте второй аккаунт Claude, Codex или agy для управления автопереключением; аккаунты Cursor переключаются автоматически при достижении лимита."
        case "Harnesses disagree (—) — pick a mode to set them all consistently.": return "Настройки агентов различаются (—) — выберите режим, чтобы установить одинаковое значение для всех."
        case "Subscription accounts switch to another enabled account at their quota limit; metered API keys stop instead.": return "Аккаунты по подписке переключаются на другой включённый аккаунт при достижении квоты; тарифицируемые API-ключи вместо этого останавливаются."
        case "When one account hits its quota, runs continue on another enabled account of the same harness.": return "Когда один аккаунт достигает квоты, выполнение продолжается на другом включённом аккаунте того же агента."
        case "Runs stop at a quota limit instead of switching accounts.": return "При достижении квоты выполнение останавливается без переключения аккаунта."
        case "Engine offline — reconnect to remove an account.": return "Движок не подключён — переподключитесь, чтобы удалить аккаунт."
        case "Engine offline — reconnect to change the account.": return "Движок не подключён — переподключитесь, чтобы изменить аккаунт."
        case "Removed from Claudexor. Claudexor removed the binding and any Claudexor-owned state or managed secret; it did not change any vendor credential for this OS user.": return "Удалено из Claudexor. Привязка, состояние Claudexor и управляемые секреты удалены; учётные данные провайдера для пользователя macOS не изменялись."
        case "This engine build does not support threads. Update Claudexor.": return "Эта версия движка не поддерживает чаты. Обновите Claudexor."
        case "The engine is out of date — restart the daemon.": return "Движок устарел — перезапустите демон."
        case "Cannot reach the engine — is the daemon running?": return "Не удалось подключиться к движку — демон запущен?"
        case "The files changed after this turn (a later run or a manual edit) —": return "Файлы изменились после этого запуска (другим запуском или вручную) —"
        case "Engine offline: reconnect before answering.": return "Движок не подключён — переподключитесь перед ответом."
        case "A previous process may still be alive. New Login and Retry stay disabled until the daemon can prove a safe replacement. API-key storage remains a separate operation.": return "Предыдущий процесс всё ещё может выполняться. Новый вход и повтор отключены, пока демон не подтвердит безопасную замену. Сохранение API-ключа остаётся отдельным действием."
        case "Deadline reached — waiting for the engine's terminal result": return "Время ожидания истекло — ожидается итоговый результат движка"
        case "Login is unavailable until setup state resolves (an active job, recovery, or an unconfirmed prior process).": return "Вход недоступен, пока не определится состояние настройки (активная задача, восстановление или неподтверждённый предыдущий процесс)."
        case "Run a fresh, non-cached Harness Doctor probe.": return "Запустить новую проверку Harness Doctor без использования кэша."
        case "Store the API key entered in the fallback field below.": return "Сохранить API-ключ, введённый ниже в резервном поле."
        case "Re-establish setup truth (re-snapshot the job / prove the process gone).": return "Повторно проверить состояние настройки и подтвердить завершение процесса."
        case "Close this auth sheet.": return "Закрыть окно авторизации."
        case "Keep Running closes this sheet without claiming the process stopped. Cancel asks the daemon again and closes only after termination is confirmed. Stay keeps the recovery details visible.": return "«Продолжить выполнение» закрывает окно, не утверждая, что процесс остановлен. «Отмена» повторно запрашивает демон и закрывает окно только после подтверждения завершения. «Остаться» оставляет сведения о восстановлении открытыми."
        case "Claudexor cannot yet prove whether a setup job is active. Keep Running leaves any accepted job in the background. Cancel first reconciles server state and closes only after confirmed termination.": return "Claudexor пока не может определить, активна ли задача настройки. «Продолжить выполнение» оставляет принятую задачу в фоне. «Отмена» сначала сверяет состояние сервера и закрывает окно только после подтверждения завершения."
        case "Keep Running closes this sheet while the daemon job continues. Cancel Login waits for confirmed process termination before closing.": return "«Продолжить выполнение» закрывает окно, пока задача демона продолжает работать. «Отменить вход» ждёт подтверждённого завершения процесса."
        case "Go": return "Перейти"
        case "localhost:3000  ·  or a URL…": return "localhost:3000  ·  или URL…"
        case "No available harness lane can receive the selected attachments.": return "Ни один доступный агент не может принять выбранные вложения."
        case "the file could not be read": return "файл не удалось прочитать"
        case "it is not a regular file": return "это не обычный файл"
        case "its size could not be determined": return "не удалось определить размер файла"
        case "the file changed while it was being read": return "файл изменился во время чтения"
        case "Remove attachment": return "Удалить вложение"
        case "This historical thread used a retired access profile. Choose an active profile to continue.": return "Этот старый чат использовал устаревший профиль доступа. Выберите действующий профиль для продолжения."
        case "Browser keeps this access scope; unsupported harness combinations are refused before launch.": return "Браузер использует тот же уровень доступа; неподдерживаемые комбинации агентов отклоняются до запуска."
        case "e.g. npm test": return "например npm test"
        case "model (optional, e.g. opus)": return "модель (необязательно, например opus)"
        case "claude=opus:max, cursor (or pinned JSON)": return "claude=opus:max, cursor (или закреплённый JSON)"
        case "path glob (e.g. test/**)": return "шаблон пути (например test/**)"
        case "reason (optional)": return "причина (необязательно)"
        case "One candidate with optional model review; completed changes can be applied normally.": return "Один кандидат с необязательной проверкой моделью; завершённые изменения можно применить обычным способом."
        case "N candidates in isolated envelopes, cross-reviewed, best wins.": return "Несколько кандидатов в изолированных средах с перекрёстной проверкой; выбирается лучший."
        case "One envelope repaired until gates/review are clean.": return "Одна среда дорабатывается до прохождения всех проверок."
        case "Scaffold a brand-new repo or component.": return "Создать новый репозиторий или компонент с нуля."
        case "Budget cap must be a non-negative number (in ⋯)": return "Лимит бюджета должен быть неотрицательным числом (в ⋯)."
        case "Accept risk & unblock": return "Принять риск и разблокировать"
        case "Rerun with feedback": return "Перезапустить с обратной связью"
        case "This runtime cannot host the Delegate tool belt. Update or repair the Claudexor runtime, then reconnect.": return "Эта среда выполнения не поддерживает инструменты делегирования. Обновите или восстановите Claudexor и переподключитесь."
        case "The selected harness cannot accept the Delegate tool belt. Choose a supported harness.": return "Выбранный агент не поддерживает инструменты делегирования. Выберите поддерживаемого агента."
        case "Delegate is unavailable for the selected harness and runtime. Check Harness Doctor, then try again.": return "Делегирование недоступно для выбранного агента и среды выполнения. Проверьте Harness Doctor и повторите попытку."
        case "The selected Claudexor runtime could not provide the Delegate tool belt. Update or repair the runtime, then try again.": return "Выбранная среда Claudexor не предоставила инструменты делегирования. Обновите или восстановите среду и повторите попытку."
        case "The selected harness could not accept the Delegate tool belt. Choose a supported harness, then try again.": return "Выбранный агент не смог принять инструменты делегирования. Выберите поддерживаемого агента и повторите попытку."
        case "The selected access profile could not host Delegate. Choose Full access, then try again.": return "Выбранный профиль доступа не позволяет делегирование. Выберите полный доступ и повторите попытку."
        case "One selected lane could not host Delegate and continued as ordinary Agent. Inspect that lane or choose only Delegate-capable harnesses.": return "Один выбранный агент не поддержал делегирование и продолжил работу как обычный агент. Проверьте этот маршрут или выберите только агентов с поддержкой Delegate."
        case "Delegate could not be enabled before the run started.": return "Делегирование не удалось включить до начала запуска."
        case "Delegated Claudexor run": return "Делегированный запуск Claudexor"
        case "Open parent run": return "Открыть родительский запуск"
        case "Native login setup": return "Настройка нативного входа"
        case "Smoke Test Ask": return "Тестовый запрос"
        case "Up": return "Вверх"
        case "The engine refused to serve this file.": return "Движок отказался предоставить этот файл."
        case "The latest release has no runtime-manifest.json asset.": return "В последнем релизе отсутствует runtime-manifest.json."
        case "The runtime manifest could not be parsed.": return "Не удалось прочитать манифест среды выполнения."
        case "The unpacked runtime is missing its daemon script.": return "В распакованной среде отсутствует скрипт демона."
        case "The engine is busy running jobs; the update will retry when idle.": return "Движок занят выполнением задач; обновление повторится после освобождения."
        case "The exact prior engine identity could not be verified; the running engine was not stopped.": return "Не удалось точно подтвердить предыдущую версию движка; работающий движок не был остановлен."
        case "Another engine lifecycle action is already in progress; retry the update.": return "Уже выполняется другая операция с движком; повторите обновление позже."
        case "Another runtime update is already in progress.": return "Уже выполняется другое обновление среды."
        case "no exact identity": return "точная идентификация недоступна"
        case "Could not refresh accounts and readiness": return "Не удалось обновить аккаунты и состояние готовности"
        case "Copy message": return "Копировать сообщение"
        case "Run Again requires an explicit access choice.": return "Для повторного запуска необходимо явно выбрать уровень доступа."
        case "Clear run filter": return "Сбросить фильтр запуска"
        case "Plan — no files changed": return "План — файлы не изменялись"
        case "Choose access in composer": return "Выберите уровень доступа в поле сообщения"
        case "Implemented over open plan questions — plan readiness was overridden.": return "Реализация выполнена при наличии открытых вопросов плана — проверка готовности плана была переопределена."

        default:
            return value
        }
    }
}
